version: '3'

services:
  api:
    build: ./api
    container_name: weightloss-api
    ports:
      - "5001:5000"
    volumes:
      - ./api:/opt/api
    environment:
      PYTHONBUFFERED: 1
    networks:
      - frontend
      - backend

  web:
    build: ./web
    container_name: weightloss-web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/opt/web
    environment:
      PYTHONBUFFERED: 1
    networks:
      - frontend

  db:
    image: mongo:latest
    container_name: weightloss-db
    ports:
      - '27017:27017'
    volumes:
      - /data/db:/data/db
    networks:
      - backend

networks:
  frontend:
  backend:

